[package]
name = "eventmesh-examples"
version = "0.1.0"
edition = "2021"
rust-version = "1.71"
authors = [
    "mxsm <mxsm@apache.org>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
